#pragma once

#define MBEDTLS_CIPHER_MODE_CFB
#define MBEDTLS_PKCS1_V21

#undef MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES
#define MBEDTLS_ENTROPY_HARDWARE_ALT

#if CONFIG_MBEDTLS_ECDSA_ALT_TPM
#define MBEDTLS_ECDSA_SIGN_ALT
#endif
